sudo: required

language: python

python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'

addons:
  apt:
    sources:
     - deadsnakes
     - sourceline: 'deb http://repo.aptly.info/ squeeze main'
       key_url: 'https://www.aptly.info/pubkey.txt'
    packages:
     - aptly

install:
  - pip install -r requirements.txt -r test_requirements.txt
  - pip install coveralls

before_script:
  - sudo aptly api serve -no-lock=true -listen "127.0.0.1:8080" &

script:
  - coverage run --source=pyptly -m nose2.__main__ -v

after_success:
  - coveralls
