sudo: false

language: python

python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'

install:
  - pip install -r requirements.txt -r test_requirements.txt
  - pip install coveralls
script:
  - coverage run --source=pyptly -m nose2.__main__ -v
after_success:
  - coveralls
